# Form implementation generated from reading ui file 'main_menu_gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_main_menu(object):
    """
    Class contains all gui and PyQt6 code.
    """
    def setupUi(self, main_menu) -> None:
        """
        PyQt and gui code
        :param main_menu: = none
        :return: = none
        """
        main_menu.setObjectName("main_menu")
        main_menu.resize(700, 500)
        main_menu.setMinimumSize(QtCore.QSize(700, 500))
        main_menu.setMaximumSize(QtCore.QSize(700, 500))
        self.main_menu_title = QtWidgets.QLabel(parent=main_menu)
        self.main_menu_title.setGeometry(QtCore.QRect(220, 20, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.main_menu_title.setFont(font)
        self.main_menu_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.main_menu_title.setObjectName("main_menu_title")
        self.main_menu_desc = QtWidgets.QTextBrowser(parent=main_menu)
        self.main_menu_desc.setGeometry(QtCore.QRect(140, 50, 421, 61))
        self.main_menu_desc.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.main_menu_desc.setObjectName("main_menu_desc")
        self.button_display_candidates = QtWidgets.QPushButton(parent=main_menu)
        self.button_display_candidates.setGeometry(QtCore.QRect(140, 120, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button_display_candidates.setFont(font)
        self.button_display_candidates.setObjectName("button_display_candidates")
        self.button_vote = QtWidgets.QPushButton(parent=main_menu)
        self.button_vote.setGeometry(QtCore.QRect(360, 120, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button_vote.setFont(font)
        self.button_vote.setObjectName("button_vote")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=main_menu)
        self.stackedWidget.setGeometry(QtCore.QRect(50, 200, 611, 291))
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.stackedWidget.addWidget(self.home_page)
        self.display_candidates_page = QtWidgets.QWidget()
        self.display_candidates_page.setObjectName("display_candidates_page")
        self.label_candidates_display = QtWidgets.QLabel(parent=self.display_candidates_page)
        self.label_candidates_display.setGeometry(QtCore.QRect(240, 10, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_candidates_display.setFont(font)
        self.label_candidates_display.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_candidates_display.setObjectName("label_candidates_display")
        self.text_ted_desc = QtWidgets.QTextBrowser(parent=self.display_candidates_page)
        self.text_ted_desc.setGeometry(QtCore.QRect(170, 180, 91, 101))
        self.text_ted_desc.setObjectName("text_ted_desc")
        self.text_bernie_desc = QtWidgets.QTextBrowser(parent=self.display_candidates_page)
        self.text_bernie_desc.setGeometry(QtCore.QRect(490, 180, 91, 101))
        self.text_bernie_desc.setObjectName("text_bernie_desc")
        self.label_hillary_clinton_pic = QtWidgets.QLabel(parent=self.display_candidates_page)
        self.label_hillary_clinton_pic.setGeometry(QtCore.QRect(330, 50, 121, 121))
        self.label_hillary_clinton_pic.setText("")
        self.label_hillary_clinton_pic.setPixmap(QtGui.QPixmap("../../../Downloads/hillary clinton.jpg"))
        self.label_hillary_clinton_pic.setObjectName("label_hillary_clinton_pic")
        self.text_donald_desc = QtWidgets.QTextBrowser(parent=self.display_candidates_page)
        self.text_donald_desc.setGeometry(QtCore.QRect(30, 180, 91, 101))
        self.text_donald_desc.setObjectName("text_donald_desc")
        self.label_donald_trump_pic = QtWidgets.QLabel(parent=self.display_candidates_page)
        self.label_donald_trump_pic.setGeometry(QtCore.QRect(20, 50, 121, 121))
        self.label_donald_trump_pic.setText("")
        self.label_donald_trump_pic.setPixmap(QtGui.QPixmap("../../../Downloads/Donald_Trump (1).png"))
        self.label_donald_trump_pic.setObjectName("label_donald_trump_pic")
        self.text_hillary_desc = QtWidgets.QTextBrowser(parent=self.display_candidates_page)
        self.text_hillary_desc.setGeometry(QtCore.QRect(350, 180, 91, 101))
        self.text_hillary_desc.setObjectName("text_hillary_desc")
        self.label_ted_cruz_pic = QtWidgets.QLabel(parent=self.display_candidates_page)
        self.label_ted_cruz_pic.setGeometry(QtCore.QRect(160, 50, 121, 121))
        self.label_ted_cruz_pic.setText("")
        self.label_ted_cruz_pic.setPixmap(QtGui.QPixmap("../../../Downloads/Ted-Cruz.jpg"))
        self.label_ted_cruz_pic.setObjectName("label_ted_cruz_pic")
        self.label_bernie_sanders_pic = QtWidgets.QLabel(parent=self.display_candidates_page)
        self.label_bernie_sanders_pic.setGeometry(QtCore.QRect(470, 50, 121, 121))
        self.label_bernie_sanders_pic.setText("")
        self.label_bernie_sanders_pic.setPixmap(QtGui.QPixmap("../../../Downloads/bernie sanders.jpg"))
        self.label_bernie_sanders_pic.setObjectName("label_bernie_sanders_pic")
        self.label_republican_party = QtWidgets.QLabel(parent=self.display_candidates_page)
        self.label_republican_party.setGeometry(QtCore.QRect(80, 20, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_republican_party.setFont(font)
        self.label_republican_party.setStyleSheet("background-color : tomato")
        self.label_republican_party.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_republican_party.setObjectName("label_republican_party")
        self.label_democratic_party = QtWidgets.QLabel(parent=self.display_candidates_page)
        self.label_democratic_party.setGeometry(QtCore.QRect(400, 20, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_democratic_party.setFont(font)
        self.label_democratic_party.setStyleSheet("background-color : dodgerblue")
        self.label_democratic_party.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_democratic_party.setObjectName("label_democratic_party")
        self.stackedWidget.addWidget(self.display_candidates_page)
        self.party_choice_page = QtWidgets.QWidget()
        self.party_choice_page.setObjectName("party_choice_page")
        self.label_choose_party = QtWidgets.QLabel(parent=self.party_choice_page)
        self.label_choose_party.setGeometry(QtCore.QRect(110, 30, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_choose_party.setFont(font)
        self.label_choose_party.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_choose_party.setObjectName("label_choose_party")
        self.button_republican = QtWidgets.QPushButton(parent=self.party_choice_page)
        self.button_republican.setGeometry(QtCore.QRect(120, 100, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button_republican.setFont(font)
        self.button_republican.setStyleSheet("background-color : tomato")
        self.button_republican.setObjectName("button_republican")
        self.button_democratic = QtWidgets.QPushButton(parent=self.party_choice_page)
        self.button_democratic.setGeometry(QtCore.QRect(350, 100, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button_democratic.setFont(font)
        self.button_democratic.setAutoFillBackground(False)
        self.button_democratic.setStyleSheet("background-color : dodgerblue")
        self.button_democratic.setObjectName("button_democratic")
        self.stackedWidget.addWidget(self.party_choice_page)
        self.candidate_choice_democratic_page = QtWidgets.QWidget()
        self.candidate_choice_democratic_page.setObjectName("candidate_choice_democratic_page")
        self.label_hillary_vote = QtWidgets.QLabel(parent=self.candidate_choice_democratic_page)
        self.label_hillary_vote.setGeometry(QtCore.QRect(150, 60, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_hillary_vote.setFont(font)
        self.label_hillary_vote.setStyleSheet("")
        self.label_hillary_vote.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_hillary_vote.setObjectName("label_hillary_vote")
        self.label_bernie_vote = QtWidgets.QLabel(parent=self.candidate_choice_democratic_page)
        self.label_bernie_vote.setGeometry(QtCore.QRect(150, 120, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_bernie_vote.setFont(font)
        self.label_bernie_vote.setStyleSheet("")
        self.label_bernie_vote.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_bernie_vote.setObjectName("label_bernie_vote")
        self.radiobutton_hillary_vote = QtWidgets.QRadioButton(parent=self.candidate_choice_democratic_page)
        self.radiobutton_hillary_vote.setGeometry(QtCore.QRect(330, 60, 82, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radiobutton_hillary_vote.setFont(font)
        self.radiobutton_hillary_vote.setObjectName("radiobutton_hillary_vote")
        self.radiobutton_bernie_vote = QtWidgets.QRadioButton(parent=self.candidate_choice_democratic_page)
        self.radiobutton_bernie_vote.setGeometry(QtCore.QRect(330, 120, 82, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radiobutton_bernie_vote.setFont(font)
        self.radiobutton_bernie_vote.setObjectName("radiobutton_bernie_vote")
        self.button_submit_demo = QtWidgets.QPushButton(parent=self.candidate_choice_democratic_page)
        self.button_submit_demo.setGeometry(QtCore.QRect(250, 200, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.button_submit_demo.setFont(font)
        self.button_submit_demo.setStyleSheet("background-color : dodgerblue")
        self.button_submit_demo.setObjectName("button_submit_demo")
        self.label_demo_exceptions = QtWidgets.QLabel(parent=self.candidate_choice_democratic_page)
        self.label_demo_exceptions.setGeometry(QtCore.QRect(146, 170, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_demo_exceptions.setFont(font)
        self.label_demo_exceptions.setText("")
        self.label_demo_exceptions.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_demo_exceptions.setObjectName("label_demo_exceptions")
        self.stackedWidget.addWidget(self.candidate_choice_democratic_page)
        self.candidate_choice_republican_page = QtWidgets.QWidget()
        self.candidate_choice_republican_page.setObjectName("candidate_choice_republican_page")
        self.label_donald_vote = QtWidgets.QLabel(parent=self.candidate_choice_republican_page)
        self.label_donald_vote.setGeometry(QtCore.QRect(150, 60, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_donald_vote.setFont(font)
        self.label_donald_vote.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_donald_vote.setObjectName("label_donald_vote")
        self.label_ted_vote = QtWidgets.QLabel(parent=self.candidate_choice_republican_page)
        self.label_ted_vote.setGeometry(QtCore.QRect(160, 120, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_ted_vote.setFont(font)
        self.label_ted_vote.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_ted_vote.setObjectName("label_ted_vote")
        self.radiobutton_donald_vote = QtWidgets.QRadioButton(parent=self.candidate_choice_republican_page)
        self.radiobutton_donald_vote.setGeometry(QtCore.QRect(330, 70, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radiobutton_donald_vote.setFont(font)
        self.radiobutton_donald_vote.setObjectName("radiobutton_donald_vote")
        self.radiobutton_ted_vote = QtWidgets.QRadioButton(parent=self.candidate_choice_republican_page)
        self.radiobutton_ted_vote.setGeometry(QtCore.QRect(330, 130, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radiobutton_ted_vote.setFont(font)
        self.radiobutton_ted_vote.setObjectName("radiobutton_ted_vote")
        self.button_submit_repub = QtWidgets.QPushButton(parent=self.candidate_choice_republican_page)
        self.button_submit_repub.setGeometry(QtCore.QRect(250, 200, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.button_submit_repub.setFont(font)
        self.button_submit_repub.setStyleSheet("background-color : tomato")
        self.button_submit_repub.setObjectName("button_submit_repub")
        self.label_repub_exceptions = QtWidgets.QLabel(parent=self.candidate_choice_republican_page)
        self.label_repub_exceptions.setGeometry(QtCore.QRect(170, 170, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_repub_exceptions.setFont(font)
        self.label_repub_exceptions.setText("")
        self.label_repub_exceptions.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_repub_exceptions.setObjectName("label_repub_exceptions")
        self.stackedWidget.addWidget(self.candidate_choice_republican_page)
        self.label_current_standings = QtWidgets.QLabel(parent=main_menu)
        self.label_current_standings.setGeometry(QtCore.QRect(66, 170, 581, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_current_standings.setFont(font)
        self.label_current_standings.setText("")
        self.label_current_standings.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_current_standings.setObjectName("label_current_standings")

        self.retranslateUi(main_menu)
        QtCore.QMetaObject.connectSlotsByName(main_menu)

    def retranslateUi(self, main_menu):
        _translate = QtCore.QCoreApplication.translate
        main_menu.setWindowTitle(_translate("main_menu", "voting"))
        self.main_menu_title.setText(_translate("main_menu", "U.S. Candidate Polls"))
        self.main_menu_desc.setHtml(_translate("main_menu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Welcome to the United States of America populous vote prediction. You may vote in favor of which presidential candidate you are expecting to cast your vote for in the upcoming election. *Disclaimer: This vote is not associated nor correlated to the Presidential Election and displays only information on voter opinions.</p></body></html>"))
        self.button_display_candidates.setText(_translate("main_menu", "DISPLAY CANDIDATES"))
        self.button_vote.setText(_translate("main_menu", "VOTE"))
        self.label_candidates_display.setText(_translate("main_menu", "CANDIDATES:"))
        self.text_ted_desc.setHtml(_translate("main_menu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ted Cruz</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Age: 52</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Solicitor General of Texas</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">U.S. Senator</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Attorney</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.text_bernie_desc.setHtml(_translate("main_menu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Bernie Sanders</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Age:82</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">U.S. Senator</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Mayor</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Activist</p></body></html>"))
        self.text_donald_desc.setHtml(_translate("main_menu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Donald J Trump</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Age: 77</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Businessman and</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">media personality</p></body></html>"))
        self.text_hillary_desc.setHtml(_translate("main_menu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Hillary Clinton</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Age: 76</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">67 Secretary of State</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">U.S. Senator</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">First Lady</p></body></html>"))
        self.label_republican_party.setText(_translate("main_menu", "REPUBLICAN PARTY"))
        self.label_democratic_party.setText(_translate("main_menu", "DEMOCRATIC PARTY"))
        self.label_choose_party.setText(_translate("main_menu", "Choose which party you would like to vote for."))
        self.button_republican.setText(_translate("main_menu", "REBUPBLICAN"))
        self.button_democratic.setText(_translate("main_menu", "DEMOCRATIC"))
        self.label_hillary_vote.setText(_translate("main_menu", "Hillary CLinton"))
        self.label_bernie_vote.setText(_translate("main_menu", "Bernie Sanders"))
        self.radiobutton_hillary_vote.setText(_translate("main_menu", "VOTE"))
        self.radiobutton_bernie_vote.setText(_translate("main_menu", "VOTE"))
        self.button_submit_demo.setText(_translate("main_menu", "SUBMIT"))
        self.label_donald_vote.setText(_translate("main_menu", "Doland Trump"))
        self.label_ted_vote.setText(_translate("main_menu", "Ted Cruz"))
        self.radiobutton_donald_vote.setText(_translate("main_menu", "VOTE"))
        self.radiobutton_ted_vote.setText(_translate("main_menu", "VOTE"))
        self.button_submit_repub.setText(_translate("main_menu", "SUBMIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_menu = QtWidgets.QDialog()
    ui = Ui_main_menu()
    ui.setupUi(main_menu)
    main_menu.show()
    sys.exit(app.exec())
